### ISSUE TITLE
MSI command line argument to set install path

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/l2tdevtools#100]
Note: Issues are disabled in the l2tbinaries repo. So I am adding it here.

The msi installer files created in the l2tbinaries repo does not allow you to change the install location from command line. The TARGETDIRX property allows you to change the path, but there is no way to set it to use that path instead of the path found in the Window's registry.

I am trying to create a script that automatically installs all the windows binary files found in the l2tbinaries repository into a virtualenv.

**Comment by joachimmetz** [comment]
Try setting TARGETDIR instead, at least that is what update.py uses. https://github.com/log2timeline/l2tdevtools/blob/master/tools/update.py#L544

**Comment by dc3-plaso** [comment]
Thanks, that seems to work.
