### ISSUE TITLE
gift copr fix broken packages

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#119]
Currenly there are issues with the following packages in dev:
* [x] ~~pytz~~
  * Python 2 package name not prefixed
* [x] ~~pyparsing~~
  * Python 2 package name prefixed with python2
  * conflicting meta package removed from dev for now
```
Error: package pyparsing-2.1.10-1.fc25.noarch requires python-pyparsing = 2.1.10-1.fc25, but none of the providers can be installed
```
* [x] ~~python-zmq~~
  * Python 2 package name prefixed with python2
  * conflicting meta package removed from dev for now
```
Error: package python-ipython-console-3.2.1-8.fc25.noarch requires python-zmq, but none of the providers can be installed
```
* [x] ~~python3-requests~~
  * some dependencies are bundled into source, should provide them separately
  * removed from dev for now

* [x] ~~dtfabric~~

**Comment by joachimmetz** [comment]
@berggren FYI

**Comment by berggren** [comment]
Ack, will take a look.

**Comment by joachimmetz** [comment]
Fix dtfabric packaging
```
Installed (but unpackaged) file(s) found:
   /usr/share/dtfabric/definitions/avrf.yaml
   /usr/share/dtfabric/definitions/core.yaml
   /usr/share/dtfabric/definitions/guid.yaml
   /usr/share/dtfabric/definitions/lnk.yaml
   /usr/share/dtfabric/definitions/mdmp.yaml
```

**Comment by joachimmetz** [comment]
dtfabric no longer ships data files
