### ISSUE TITLE
Create ppa meta-package to make updating easier

### ISSUE THREAD

**Issue by rbdebeer-zz** [log2timeline/l2tdevtools#180]
Make a ppa meta package including all packages needed to apt-get update/upgrade easier.

**Comment by joachimmetz** [comment]
Per conversation the idea is to have a meta package for the plaso dependencies.

**Comment by joachimmetz** [comment]
first iteration in https://github.com/joachimmetz/plaso/tree/dpkg

**Comment by joachimmetz** [comment]
This could be accomplished by `apt-get -y install --no-install-recommends $(apt-cache depends python3-plaso | grep Depends | sed 's/.*ends:\ //' | tr '\n' ' ')` as used in https://github.com/log2timeline/l2tdevtools/pull/868

Once installed `apt-get upgrade` should keep them up to date
