### ISSUE TITLE
Add packaging code for GRR API 

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#233]
https://github.com/google/grr/tree/master/api_client/python

This is to support dftimewolf, among other things.

**Comment by Onager** [comment]
The GRR API client requires a newer version of the protobuf library than is available in Xenial and Trusty.

**Comment by joachimmetz** [comment]
@Onager what is the status of this?

**Comment by joachimmetz** [comment]
GRR API client requires IPython ?
https://github.com/google/grr/blob/master/api_client/python/setup.py#L78

**Comment by joachimmetz** [comment]
This seems to have been completed.
