### ISSUE TITLE
review script: automatically set reviewer

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#255]
To replace codereview functionality have the review script automatically set reviewer for 'create-pr'

References: https://developer.github.com/v3/pulls/review_requests/

**Comment by Onager** [comment]
Another option: https://cloud.google.com/community/tutorials/github-auto-assign-reviewers-cloud-functions

**Comment by joachimmetz** [comment]
if you want a full github based workflow you'll need to do the webhook any way. IMHO that is a separate issue.

**Comment by joachimmetz** [comment]
This functionality is implemented now
