### ISSUE TITLE
"Unsupported download URL" tracebacks when attempting "python tools/build.py download"

### ISSUE THREAD

**Issue by johngalvin** [log2timeline/l2tdevtools#262]
Context: I'm trying to set up a new development environment and dependencies for plaso, following the instructions at https://github.com/log2timeline/l2tdevtools/wiki/Build-script#build-target-download.

I suspect there is a bug or some data staleness due to the following:

```
l2tdevtools$ PYTHONPATH=. python tools/build.py download
[elided]
[INFO] Processing: xz
Traceback (most recent call last):
  File "tools/build.py", line 359, in <module>
    if not Main():
  File "tools/build.py", line 337, in Main
    if not project_builder.Build(project_definition):
  File "tools/build.py", line 178, in Build
    project_definition.download_url))
ValueError: Unsupported download URL: http://tukaani.org/xz/.
```

I received similar for the Timesketch package. I got things passing locally by adjusting the projects.ini download_url value for timesketch to "https://github.com/google/timesketch/releases", and for xz to use an (as yet) unverified mirror I found at https://github.com/xz-mirror... not sure if that's safe or if we want a new DownloadHelper for tukaani.org directly.

Before I send a fix, can someone please let me know if:

1. Using the mirror above is safe, or if a TukaaniDownloadHelper is the preferred fix
1. Whether this the right thing to do, or if I'm working off known-outdated docs and holding this completely wrong :)

Thanks!
\- John

**Comment by johngalvin** [comment]
Hey @joachimmetz, Aaron suggested I tag you here -- can you give me some guidance on the above whenever you have a minute? Thanks!

**Comment by joachimmetz** [comment]
@johngalvin try adding `--preset plaso`

```
python tools/build.py --preset plaso download
```

http://tukaani.org/xz/ is needed for building libzma which is used by one of the pyzma implementation, for which might have not been fully implemented in l2tdevtools yet.

**Comment by joachimmetz** [comment]
@johngalvin I'm also wondering if you really need to build / download the dependencies yourself. I opt you reach out via chat to discuss your needs for the build script in more detail.

**Comment by johngalvin** [comment]
Using `--preset plaso` seems to have resolved these errors; `--preset timesketch` does not present the same errors as I originally received for timesketch, and I'm using virtualenv now anyway.

This can be probably closed in favor of https://github.com/log2timeline/l2tdevtools/issues/53. Thanks!
