### ISSUE TITLE
Remove sphinx index generation from review tool

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#275]
* [x] ~~remove sphinx apidoc support~~
  * ~~https://codereview.appspot.com/340870043~~
* [x] ~~added readthedocs github webook~~
* [x] remove readthedocs trigger
  * https://codereview.appspot.com/335680043/

**Comment by joachimmetz** [comment]
@Onager can we safely remove the readthedocs trigger at this point ?
