### ISSUE TITLE
Python backports packages missing namespace init

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#277]
#179 fixed the overlapping files, but now there's no module init.

Noted https://github.com/log2timeline/plaso/issues/1747

Ref https://salsa.debian.org/science-team/python-backports.weakref for debian packaging strategies to avoid this.

* [x] fix unbuntu
* [x] add backports.lzma to win32 and win64 - not feasible
* [x] add backports.lzma to macos

**Comment by joachimmetz** [comment]
Another reference http://launchpadlibrarian.net/277243093/backports.ssl-match-hostname_3.4.0.2-1_3.5.0.1-1.diff.gz

Determining if adding `--namespace backports` is sufficient

**Comment by joachimmetz** [comment]
additional changes to make backports.lzma architecture dependent build
https://codereview.appspot.com/340860043/

**Comment by joachimmetz** [comment]
TODO fix: https://travis-ci.org/log2timeline/dfvfs/jobs/351961007#L771
```
dpkg: error processing archive /var/cache/apt/archives/python-backports.functools-lru-cache_1.4-3ppa1~trusty_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/backports/__init__.py', which is also in package python-backports.lzma 0.0.10-5ppa1~trusty
```

**Comment by joachimmetz** [comment]
>  add backports.lzma to win32 and win64

requires xz which is not VS2008 compatible

**Comment by joachimmetz** [comment]
Closing issue
