### ISSUE TITLE
Add ZeroMQ to projects

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#29]
Ref https://github.com/log2timeline/plaso/issues/193

* [x] Win32 build
* [x] Win64 build
  * libsodium compile errors VS2010 (POSIX type replacements)
  * zeromq compile errors VS2010 (POSIX type replacements)
  * alternative is to use one of the official releases https://github.com/zeromq/pyzmq/releases
* [x] Mac OS X build
* [x] Ubuntu build - Already provided by Ubuntu too much packages dependent on ZeroMQ to cleanly distribute via GIFT
* [x] Travis CI - Ubuntu precise (backport 14 from trusty to precise)
  * build cython architecture independent with --no-cython-compile, removed python-cffi dependency
  * need amd64 build

**Comment by joachimmetz** [comment]
backport 14 from trusty to precise for travis

**Comment by joachimmetz** [comment]
pyzmq requires libzmq

libzmq requires libsodium

**Comment by joachimmetz** [comment]
Only remaining small issue with include header order on VS2010 causing the build to fail: https://github.com/zeromq/pyzmq/issues/885 

removing buildutils/include_win32/stdint.h is a work around.
