### ISSUE TITLE
Split dependency writers from update-dependencies script

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#320]
The monolithic file makes it harder to review, and makes test coverage less transparent.

**Comment by joachimmetz** [comment]
Instead of having a per class dependency writer I opt to group them per "function" e.g. have single travis dependency writer file.
* https://codereview.appspot.com/340630043/

Otherwise you create the same issue (harder to review) across many files.

**Comment by Onager** [comment]
The dependency writers have been split, closing this out.
