### ISSUE TITLE
Add compatibility with Ubuntu 18.04

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#347]

**Comment by joachimmetz** [comment]
Unclear what this issue fully entails, but for now assuming to provide builds of plaso dependencies for Ubuntu 18.04

Added bionic 18.04 as target distribution: https://codereview.appspot.com/341290043

**Comment by joachimmetz** [comment]
Build dpkg source packages for bionic, pushed to launchpad testing to see what need to be fixed.

**Comment by joachimmetz** [comment]
Added AppVeyor Ubuntu 16.04 and 18.04 tests
https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/
https://www.appveyor.com/docs/build-environment/

**Comment by joachimmetz** [comment]
Fix for funcsigs: https://github.com/log2timeline/l2tdevtools/pull/499

**Comment by joachimmetz** [comment]
Pycrypto issue was already fixed, uploaded new package.
