### ISSUE TITLE
remove binplist from GIFT and l2tdevtools

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#350]
Seeing that plaso no longer uses binplist remove it from GIFT and l2tdevtools

* [x] ~~remove from GIFT PPA~~
* [x] ~~remove from GIFT COPR~~
* [x] remove from projects list
  * https://codereview.appspot.com/344920043/
* [x] remove from presets
  * https://codereview.appspot.com/344920043/
* [x] ~~remove from l2tbinaries~~

**Comment by joachimmetz** [comment]
@Onager @tomchop @grrrrrrrrr does this affect dftimewolf and or GRR ?

**Comment by grrrrrrrrr** [comment]
I don't think GRR is affected either.
