### ISSUE TITLE
Configure codecov pull request reports to be more useful

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#353]
It looks like this can be done either in the "team yaml" or per repository. Ref: https://docs.codecov.io/docs/codecov-yaml

- [ ] Consider turning off Pull Request Comments
- [x] Decide on and set a threshold for pull request status

**Comment by Onager** [comment]
Threshold set at 1%, but we're going to try the comments with a different configuration for a bit longer.

**Comment by joachimmetz** [comment]
I would prefer us to put this in a codecov configuration such as: https://github.com/log2timeline/plaso/pull/2033

Also see: https://docs.codecov.io/v4.3.6/docs/commit-status

**Comment by Onager** [comment]
Codecov reports haven't been troublesome for a while, and the configuration was moved to l2tdevtools, per https://github.com/log2timeline/l2tdevtools/pull/361
