### ISSUE TITLE
recent changes for GRR break building dpkg

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#387]
The additions in https://github.com/log2timeline/l2tdevtools/blame/master/l2tdevtools/build_helpers/dpkg.py#L165

```
    if self.version_suffix and self.distribution:
      deb_orig_source_filename = '{0:s}_{1!s}{2:s}~{3:s}.orig.tar.gz'.format(
          project_name, project_version, self.version_suffix, self.distribution)
```

break building dpkg, e.g. wrong orig filename is created for libewf

@Onager what specific package needs these changes?

**Comment by joachimmetz** [comment]
Per conversation with @Onager, apparently new versions of Ubuntu require these changes. We need to detect the Ubuntu toolchain version and select the appropriate naming convention.

**Comment by joachimmetz** [comment]
Trusty `debuild --version`
```
This is debuild, from the Debian devscripts package, version 2.14.1ubuntu0.1
This code is copyright 1999-2003 by Julian Gilbey <jdg@debian.org>,
all rights reserved.
Based on a shell-script program by Christoph Lameter.
This program comes with ABSOLUTELY NO WARRANTY.
You are free to redistribute this code under the terms of the
GNU General Public License, version 2 or later.
```

**Comment by joachimmetz** [comment]
@Onager which version of Ubuntu did you ran this on? Xenial still requires the "old" naming convention

**Comment by Onager** [comment]
@joachimmetz This was a while ago, but I'm pretty sure it was xenial, not bionic where this came up.

**Comment by joachimmetz** [comment]
bionic also has issues with these changes, reverting https://github.com/log2timeline/l2tdevtools/pull/676
