### ISSUE TITLE
improve review scripts

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#40]
- [x] ~~Fix git pull issue on close~~
- [x] ~~fix version not being updated on merge~~
- [x] ~~Check why the rietveld close issue is still not working~~
  - ~~missing cookie jar - use OAuth instead~~
- [x] ~~change/remove missing test file script~~
- [x] ~~[Move review scripts to Python - to support Windows](https://codereview.appspot.com/269830043/)~~
  - ~~update l2tdevtools script with plaso scripts~~
  - ~~fix limitation in merge script that CL description cannot contain a ':'~~
  - ~~add a submitted comment to code review~~
  - ~~change http:// to https:// where possible~~
- [x] ~~[fix issue argparse yielding different results when run from review.py](https://github.com/log2timeline/plaso/issues/480)~~
- [x] ~~review.py add functionality to "test"~~
- [x] ~~review.py add option for unattended mode - do not ask for confirmation~~
- [x] ~~[review.py create - do not generate '[project_name]' in PR description](https://codereview.appspot.com/290320043/)~~
- [x] ~~document usage of `BROWSER` environment variable~~
- [x] ~~review.py "lint" add option to lint all files~~
- [x] ~~update dfwinreg scripts~~
  - ~~removed shell scripts~~
- [x] ~~update dfvfs scripts~~
  - ~~removed shell scripts~~
- [x] ~~update plaso scripts~~
  - ~~removed shell scripts~~
- [x] ~~Provide pylint in l2tbinaries~~
- [x] ~~https://codereview.appspot.com/309000043/~~
  - ~~create - check if review file exists first~~
  - ~~close - notify if review file is missing or codereview issue cannot be closed~~
  - ~~close - support user:branch as input besides branch~~
  - ~~added update-authors functionality~~
- [x] ~~[add lint_and_test option](https://codereview.appspot.com/313250043)~~
- [x] ~~fix issue with create --nobrowser~~
  - `Create aborted - unable to create codereview issue.`
  - Issue created message not at the start of the line

Remaining items moved to: https://github.com/log2timeline/l2treviewtools/issues/22

**Comment by rgayon** [comment]
Only run python tests when python code was modified
