### ISSUE TITLE
update elasticsearch-py to latest 5.5.x version

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#408]
* [x] ~~fix upper bound version check~~
  * https://github.com/log2timeline/l2tdevtools/pull/409
* [ ] update elasticsearch-py to latest 5.5.x version
* [ ] rename module import to elasticsearch5
* [ ] rename package to elasticsearch5

**Comment by rgayon** [comment]
#409 broke building on windows, but that's probably expected

**Comment by joachimmetz** [comment]
Issue was addressed
