### ISSUE TITLE
Version check of idna failing on Travis-CI MacOS

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#419]
From: https://travis-ci.org/log2timeline/l2tbinaries/jobs/413911357#L2038

```
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna-2.7-py2.7.egg-info/PKG-INFO'
```

**Comment by Onager** [comment]
Possibly relevant:
https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce

**Comment by joachimmetz** [comment]
How I (now) interpret the error is that the version check of idna fails not the installation

**Comment by joachimmetz** [comment]
```
-rwx------  1 user  staff  10565 Jun 30 19:52 build/idna-2.7/tmp/Library/Python/2.7/site-packages/idna-2.7-py2.7.egg-info/PKG-INFO
```

**Comment by joachimmetz** [comment]
https://travis-ci.org/log2timeline/l2tbinaries/jobs/414214046

```
Fatal Python error: PyThreadState_Get: no current thread
/Users/travis/.travis/job_stages: line 78:  3855 Abort trap: 6           ./utils/check_dependencies.py
```

**Comment by joachimmetz** [comment]
Only updated win32 and win64 of dev and tests fail https://travis-ci.org/log2timeline/l2tbinaries/jobs/414371761. So this is very likely related to changes on Travis-CI itself.

**Comment by joachimmetz** [comment]
Moved psutil issue to https://github.com/log2timeline/l2tdevtools/issues/421, closing this one.
