### ISSUE TITLE
l2tbinaries add win64 AppVeyor test

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#424]
add win64 AppVeyor test to l2tbinaries

**Comment by joachimmetz** [comment]
Changed for l2tdevtools https://github.com/log2timeline/l2tdevtools/pull/445

**Comment by joachimmetz** [comment]
Added tests to l2tbinaries: https://ci.appveyor.com/project/Log2timeline/l2tbinaries/build/4
