### ISSUE TITLE
Look into work-around for conflicting packages on Ubuntu and Debian

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#465]
Default Ubuntu and Debian package names conflict with some packages in GIFT PPA.

Some versions in Ubuntu and Debian are ancient.

Look into https://www.debian.org/doc/debian-policy/ch-relationships.html to have dpkg deal with conflicts more elegantly.

**Comment by joachimmetz** [comment]
This should likely do the job
```
Conflicts: conflicting_package_name
Replaces: conflicting_package_name
```

**Comment by joachimmetz** [comment]
conflicting dependency names:

* libbde1 => libbde, python-libbde => libbde-python
* libesedb1
* libevt1
* libevtx1
* libewf2
* libfsntfs1
* libfvde1
* libfwnt1
* libfwsi1
* liblnk1
* libmsiecf1
* libolecf1
* libqcow1
* libregf1
* libscca1
* libsigscan1
* libsmdev1
* libsmraw1
* libvhdi1
* libvmdk1
* libvshadow1
* libvslvm1
* plaso => python-plaso, plaso-data, plaso-tools
* python-tsk

...
libyara3{a} python-bittorrent{a} 
```

**Comment by qinidema** [comment]
As you've removed the libewf2 'fake package' (from libewf 20140805 and onwards) to e.g. have sleuthkit and python-plaso installed at the same time I believe your new libewf should have 'Provides: libewf2' section in addition to 'Conflicts' and 'Replaces', as the sleuthkit is still depending on libewf2 and not libewf.

**Comment by joachimmetz** [comment]
Ack, thx I have a look at this scenario. Though I had some issues with Provides in the past, not behaving as I would expect it to. 

Note to self: https://www.debian.org/doc/debian-policy/ch-relationships.html#virtual-packages-provides.

**Comment by qinidema** [comment]
> 
> 
> Ack, thx I have a look at this scenario. Though I had some issues with Provides in the past, not behaving as I would expect it to.
> 

That is the exactly same problem that I'm facing right now :D So, the docs are stating

>
>If a relationship field has a version number attached, only real packages will be considered to see whether the relationship is satisfied (or the prohibition violated, for a conflict or breakage). In other words, if a version number is specified, this is a request to ignore all Provides for that package name and consider only real packages. The package manager will assume that a package providing that virtual package is not of the “right” version. A Provides field may not contain version numbers, and the version number of the concrete package which provides a particular virtual package will not be considered when considering a dependency on or conflict with the virtual package name.
>

And the sleuthkit is the example of such a package which is requiring the particular version in depends
>
>Depends: libafflib0v5 (>= 3.7.6), libc6 (>= 2.14), libewf2 (>= 20090606)
>
So, sadly, the package with 'Provides' is just ignored here. I think that the best bet is to get back to 'fake', but real (not virtual) libewf2 package. Could you provide the newer versions of it in your repo?

**Comment by qinidema** [comment]
I think you can do something like the following:
1. Remove the 'Replaces' and 'Conflicts' from libewf package, but add 'Depends' with the newer version of libewf2 (to have your fake libewf2 to be installed as a dependency)
2. Resurrect the fake libewf2 package with 'Replaces' libewf2 ( <= $OLD_UBUNTU_VERSION) and 'Conflicts' with the lower versions (to make sure the old libewf2 will not be installed again and to avoid the conflict). Additionally you can add the 'Depends' on your real libewf here for the users that for any reason want to install your newer libewf version with the real library.
So the users that would like to install the python-plaso package will get their old libewf2 uninstalled properly and replaced by your fake version, and still the old sleuthkit package would be happy to see your 'fake' libewf2.

**Comment by joachimmetz** [comment]
How virtual packages are used by Debian https://www.debian.org/doc/packaging-manuals/virtual-package-names-list.txt

**Comment by moutonf** [comment]
Is there a current workaround on this? I am struggling to get SIFT working a functional install of Plaso. Any temporary workaround would be great.

**Comment by joachimmetz** [comment]
@moutonf this highly depends on how you are installing plaso. The easy way, remove the offending (typically highly outdated) packages and install plaso from GIFT PPA. Another way install plaso inside docker, no issues with conflicting outdated system of SIFT provided packges.

**Comment by moutonf** [comment]
@joachimmetz , this is most likely not the correct place, but I think several people run into this issue thread when they are trying to install plaso on a fresh Ubuntu install where SIFT is just installed. After the SIFT installation it complains that the following packages has failed:

sleuthkit
xmount
autopsy

All of them fail due to libewf2 dependency. However, I require to xmount some evidence files before I can run plaso overthem. Is there anyway I can get both plaso and xmount working?

**Comment by joachimmetz** [comment]
@moutonf this is the first I learn about the issue on SIFT, I have other obligations at this point but will try to have a look later. At first glances it looks like SIFT is providing packages that conflict in configuration?

I see no mention of people using the GIFT PPA packages (not sure if SIFT does under the hood but last time I looked they used a mix of various installation techniques that could conflict with one and other). That the GIFT packages conflict with those provide by Debian/Ubuntu is why we are tracking this issue.

**Comment by moutonf** [comment]
@joachimmetz that will be greatly appreciated. From my personal debugging, I have found the following:

The packages sleuthkit, xmount, autopsy require libewf2 version 20140608-6 which is on the ubuntu repos. The gift repo has version 20140804-1ppa1~xenial, hence why there is a conflict. The GIFT repo has higher priority for installs, and thus when you attempt to install any of the three packages it fails as it attempts to intsall the GIFT repo version of libewf2. Forcing it to install the ubunto repo of libewf2 works, however, it then removes plaso again...

**Comment by joachimmetz** [comment]
I understand this issue (hence this bug) but what does this have to with SIFT? does it blindly use GIFT without testing other packages they provide? 

Also there is another issue why changes were made is that if that an old libewf2 is installed it is not removed by newer versions of libewf and per previous comments dpkg (apt) does not have a good solution for this as far as we know. Only a work-around has proposed that likely re-introduces the previous issue.

**Comment by moutonf** [comment]
I wont say the blindly use GIFT, it is more that plaso gets installed first and in doing that it breaks the installs for xmount, sleuthkit and autopsy. If you take a fresh install of ubuntu 16.04 and then use sift-cli to install sift, you should run into exactly the same issue, where those 3 packages fail to install.

**Comment by ekristen** [comment]
Hi @joachimmetz I'm looking into this from my side as well. AFAIK SIFT doesn't provide autopsy, but we do provide a different libtsk and sleuthkit, but from what I can tell at the the moment is that neither of those pin to a specific version of libewf, just require libewf-dev for build.

I think this might be a versioning issue with the libewf2 package that is shipped by ubuntu and this might be taking priority for some reason. I need to do more testing to figure it out, this is just all speculation based on logs and errors at the moment.

**Comment by joachimmetz** [comment]
> but we do provide a different libtsk and sleuthkit, but from what I can tell at the the moment is that neither of those pin to a specific version of libewf, just require libewf-dev for build.

So you'll create a binary dependency on the shared object this way, which should be represented in the dpkg config. Can you check if the dpkg build tools do not automatically add a dependency on libewf or libewf2 for that matter. Or link me to your dpkg build config.

> I think this might be a versioning issue with the libewf2 package that is shipped by ubuntu and this might be taking priority for some reason.

this will depend on the priority settings of the PPAs

> it is more that plaso gets installed first and in doing that it breaks the installs for xmount, sleuthkit and autopsy

This is deliberate, since the default available version sleuthkit in particular is ancient

**Comment by qinidema** [comment]
> This is deliberate, since the default available version of sleuthkit in particular is ancient

So, there is another way: you can provide the newer versions of sleuthkit and xmount build against the newer libewf. I know, I may be asking for too much effort, but I can provide some help here. And as for me that is the best way, because you are solving two problems at once (the second one gives you the newer forensic tools in the distro, removing the ancient ones).

**Comment by joachimmetz** [comment]
Unfortunately I don't have infinite bandwidth. Also what breaks after updating these? IMHO to fix this we need better alignment between Debian/Ubuntu, SIFT and projects such as those of log2timeline. The reason why we started our own PPA is that we want to spend time on moving the DF field forward not maintaining its legacy. Especially if project owners don't seem to want to maintain their own projects.

We've reached out to SIFT in 2015, warned them about potential breakage and proposed closer alignment. Remained quiet after that until the recent breakage.

We reached out to one of Debian DF projects maintainers (as far as I can tell responsible for most of them) https://github.com/log2timeline/l2tdevtools/issues/487. Unfortunately they'll focus on updating unstable, but no answer on solutions to structurally address this. 

@qinidema if you have other suggestions?

**Comment by qinidema** [comment]
@joachimmetz I've just read all the conversation in https://github.com/sans-dfir/sift/issues/337 and that's great you've collaborated to sort this out! Thank you a lot. As for me, I've just sticked with the somewhat dirty solution in https://github.com/log2timeline/l2tdevtools/issues/465#issuecomment-457606029. As for the breakage there is not so much packages that depends on xmount and sleuthkit:
```
[user@box] ~ $ apt-cache rdepends sleuthkit
sleuthkit
Reverse Depends:
  dstat
  mac-robber
  mac-robber
  mac-robber
  mac-robber
  forensics-all
  autopsy
  binwalk
[user@box] ~ $ apt-cache rdepends xmount
xmount
Reverse Depends:
  afflib-tools
```
As for me, I'm using sleuthkit (ofc), xmount, binwalk, mac-robber and afflib-tools. Even without rebuilding them these are working fine with that workaround that I've used.
mac-robber and autopsy are maintained by sleuthkit devs, so there must be no problems with the newer sleuthkit itself.
binwalk just calls the tsk_recover binary, as can be seen in https://github.com/ReFirmLabs/binwalk/blob/720f770e0416ea3b186e24f517991baa4b82aef2/src/binwalk/config/extract.conf#L68
afflib-tools just contains xmount in ints 'Suggests' section, both depends on afflib (libafflib0v5).

**Comment by joachimmetz** [comment]
So what I think is helpful here is for SIFT to figure out what set of packages they want to support and for the project to take a more devops approach. 

1. Add automated integration testing for new builds. We have GIFT dev PPA track that is used to regular push updates of dependencies and detect breakage. SIFT could adopt the same approach.

2. Automate builds of new versions of packages. For log2timeline we create l2tdevtools to minimize the effort to build dependencies, and are working on continuous builds. The same can be done for SIFT.

**Comment by joachimmetz** [comment]
@ekristen FYI

**Comment by joachimmetz** [comment]
The recommendation for people running to these issues is to use docker. Docker allows you to build a fairly hermetic environment without having to wait for distro maintainers to push updates.
