### ISSUE TITLE
Remove mock hardcoded dependency

### ISSUE THREAD

**Issue by tomchop** [log2timeline/l2tdevtools#469]
It seems the dependency check for `mock` is hardcoded in dftimewolf's `dependencies.py`, which causes issues in python3 where the dependency is not needed.

@Onager says it might already be fixed.

**Comment by joachimmetz** [comment]
Mock is still hard coded in https://github.com/log2timeline/l2tdevtools/blob/master/l2tdevtools/dependencies.py#L138

Possible solutions:

* move mock to test_dependencies.ini
* move mock to dependencies.ini and flags as test dependency

**Comment by joachimmetz** [comment]
* [ ] add support to l2tdevtools
* [ ] update dfdatetime
  * https://github.com/log2timeline/dfdatetime/pull/127
* [ ] update dfwinreg
* [ ] update dfvfs
* [ ] update plaso
* [ ] update l2tpreg

**Comment by joachimmetz** [comment]
Mock is now set by test_dependencies.ini
