### ISSUE TITLE
Update plaso in debian upstream repositories

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/l2tdevtools#487]
plaso in debian is outdated, they currently have 1.5.1 as the last version. it would be nice have a debian repository up to date, either [upstream](https://packages.debian.org/buster/plaso) or ppa like.

**Comment by joachimmetz** [comment]
I've reached out @hillu via email, but no response so far, maybe github will do the trick:

```
Hello Hilko,

I'm reaching out to you since you seem one of the active maintainers
of forensics packages in Debian. You might remember me, if not I the
maintainer of various projects you've packaged. Feel free to loop in
other people you think are relevant for this conversation.

Thanks for getting them packaged into Debian, however I've noticed
that some of them have not been updated in quite a while e.g.
https://tracker.debian.org/pkg/plaso. To the point where I'm thinking
it is not responsible to keep these old versions around anymore e.g.
that 4.4.0 of sleutkit is considered stable
https://tracker.debian.org/pkg/sleuthkit (there have been tons of
fixes for serious bugs for this project)

I was wondering if there is anything we can do to from the project
side, so can have a more recent version of the tooling available in
Debian.

E.g. does Debian provide a similar platform of Ubuntu launchpad where
we can provide continuous integration testing builds?

Also I would like to chat about the current package name of plaso. We
are moving to Python3 and it might be good practice to change the
package into python-plaso, python3-plaso, plaso-data, plaso-tools (or
equiv)

Kind regard,
```

In the meantime I'll look into obsoletes and replaces options in dpkg packing files to just force remove out of date versions of conflicting package names.

**Comment by hillu** [comment]
@joachimmetz ping reminder noted, will answer via mail.

@aguilajesus It is not possible to update plaso to a new release in the current stable Debian release (9.x "stretch"), however, I am going to work to ensure that the next Debian release (10, "buster") will ship with a then-up-to-date version.

**Comment by joachimmetz** [comment]
Marking as blocked on Debian maintainers, will pursue https://github.com/log2timeline/l2tdevtools/issues/465 as work around.

**Comment by joachimmetz** [comment]
Looks like this is WIP https://tracker.debian.org/pkg/plaso, closing this issue

**Comment by hillu** [comment]
Yeah. Sorry for taking so long.

**Comment by joachimmetz** [comment]
@hillu no problem, per email, also let us know how we can closer align efforts.
