### ISSUE TITLE
merge_submit script (and maybe others?) fails if the description field of the code review contains double quotes

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#49]
Noticed with issue https://codereview.appspot.com/281870043/

**Comment by Onager** [comment]
Error is "unable to find change list with number", and is probably around here: https://github.com/log2timeline/l2tdevtools/blob/master/utils/merge_submit.sh#L146

**Comment by joachimmetz** [comment]
The sh scripts have been superseded by review.py and are kept for historical purposes. Closing issue.
