### ISSUE TITLE
Add packaging code for Turbinia

### ISSUE THREAD

**Issue by tomchop** [log2timeline/l2tdevtools#595]
https://github.com/google/turbinia

**Comment by joachimmetz** [comment]
Per https://github.com/google/turbinia/blob/master/requirements.txt

* filelock
* google-api-core>=1.2.1,<=1.4.0
* google-cloud-datastore==1.7.0
* google-api-python-client>=1.6.2
* google-cloud-pubsub==0.35.4
* google-cloud-storage==1.13.0
* google-cloud-core==0.28.1
* oauth2client
* psq
* six
* urllib3

**Comment by joachimmetz** [comment]
Marking as blocked oauth2client is deprecated https://github.com/google/turbinia/issues/373 and per @tomchop there are likely more dependency clean ups planned around Jun/Jul

**Comment by joachimmetz** [comment]
Unfortunately there are a lot of sub dependencies here

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/l2tdevtools/pull/726

**Comment by joachimmetz** [comment]
```
Unpacking python-google-cloud-storage (1.16.1-1ppa1~bionic) ...
dpkg: error processing archive /tmp/apt-dpkg-install-M7bsAu/78-python-google-cloud-storage_1.16.1-1ppa1~bionic_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/google/cloud/storage/__init__.py', which is also in package python-google-cloud-datastore 1.16.1-1ppa1~bionic
```

**Comment by joachimmetz** [comment]
need update version of protobuf https://github.com/log2timeline/l2tdevtools/issues/731

**Comment by joachimmetz** [comment]
Taking another stab at this https://github.com/log2timeline/l2tdevtools/pull/837

**Comment by joachimmetz** [comment]
Handle auto-generated python3-googleapi dependency
