### ISSUE TITLE
No wiki page for tools/update-dependencies.py

### ISSUE THREAD

**Issue by alimez** [log2timeline/l2tdevtools#612]
There is no documentation for tools/update-dependencies.py in  https://github.com/log2timeline/l2tdevtools/wiki.

**Comment by joachimmetz** [comment]
For now there is `update-dependencies.py --help` but we'll have a look at add the missing documentation

**Comment by joachimmetz** [comment]
page added https://github.com/log2timeline/l2tdevtools/wiki/Update-dependencies-script
