### ISSUE TITLE
Build errors with dpkg-source target

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#647]
Command line:
`PYTHONPATH=. python tools/build.py --preset plaso dpkg-source`

Build.log content is 
```
tail cannot open 'debian/changelog' for reading: No such file ore directory
dpkg-buildpackage: error tail of debian/changelog gave error exit status 1
```
I'm guessing this might relate to https://github.com/log2timeline/l2tdevtools/commit/f9fa37bf302e7767f3e1c2d690c952661d3e866d given it changed the build directory, and this looks like the script is not in the directory it expects to be in.

**Comment by joachimmetz** [comment]
This looks like an issue with running `dpkg-buildpackage` however `dpkg-source` should run `debuild`?

Maybe related: https://ubuntuforums.org/showthread.php?t=1405550

What project is it failing on?

**Comment by Onager** [comment]
At https://github.com/log2timeline/l2tdevtools/blob/eb1b2c1e1fc2fef10b3ad30fd35829f644b62f93/l2tdevtools/build_helpers/dpkg.py#L1024
os.getcwd() is the l2tbuilds directory, rather than the package directory

**Comment by joachimmetz** [comment]
correct because the command is executed as: `(cd sourcedir && command)`
https://github.com/log2timeline/l2tdevtools/blob/eb1b2c1e1fc2fef10b3ad30fd35829f644b62f93/l2tdevtools/build_helpers/dpkg.py#L1025

**Comment by Onager** [comment]
This looks to have been something particular to the environment - cleaning up build directories resolved the issue.
