### ISSUE TITLE
Investigate and fix pypi downloaders

### ISSUE THREAD

**Issue by Onager** [log2timeline/l2tdevtools#66]
It looks like download urls have changed, and include some unexpected elements:
https://pypi.python.org/packages/d3/8b/a82129243571dba8f37e8b488265984d86ddd881faf82745ede600627871/pylint-1.5.5.tar.gz#md5=208a6365f81ba072293539ae51614d09

**Comment by joachimmetz** [comment]
Changes already pending in: https://codereview.appspot.com/293170043/

**Comment by joachimmetz** [comment]
Changes submitted
