### ISSUE TITLE
Update Python2.7 SQLite in AppVeyor to include FTS flags

### ISSUE THREAD

**Issue by obsidianforensics** [log2timeline/l2tdevtools#732]
Some AppVeyor tests using Python2.7 are failing ([example](https://ci.appveyor.com/project/log2timeline/plaso/builds/24957071/job/p69hx8l1snxk4t2e)) because SQLite wasn't compiled with FTS3/4 support (https://www.sqlite.org/fts3.html#compiling_and_enabling_fts3_and_fts4). Not all queries fail; only ones that try to access virtual FTS tables. 

From the SQLite page above, I think these two switches `-DSQLITE_ENABLE_FTS3` and `-DSQLITE_ENABLE_FTS3_PARENTHESIS` need to be added to the compiler command line for SQLite.

**Comment by joachimmetz** [comment]
Added changes to https://github.com/log2timeline/l2tdevtools/pull/754

**Comment by joachimmetz** [comment]
l2tbinaries win32 and win64 2.7 builds updated in testing

**Comment by joachimmetz** [comment]
This has propagated to stable by now. Also 2.7 will be deprecated Jan 1. Closing issue.
