### ISSUE TITLE
add libcloudforensics build preset

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#739]
https://github.com/google/turbinia/blob/master/turbinia/lib/libcloudforensics.py#L333

```
    # Analysis software to install.
    packages_to_install = [
        'python-plaso', 'xmount', 'sleuthkit', 'libfvde-tools', 'libbde-tools',
        'plaso-tools', 'jq', 'ncdu', 'htop', 'binutils', 'upx-ucl',
        'docker-explorer-tools'
    ]
```

**Comment by joachimmetz** [comment]
@rgayon @aarontp FYI

Likely we want to add libfsapfs-tools as well? other things on the wishlist?

**Comment by rgayon** [comment]
+1 for libfsapfs
Nothing else comes to mind

**Comment by joachimmetz** [comment]
added to https://github.com/google/turbinia/pull/409 as well

**Comment by joachimmetz** [comment]
@tomchop FYI seeing your plans of making libcloudforensics stand-alone

**Comment by joachimmetz** [comment]
Per https://github.com/log2timeline/l2tdevtools/commit/18c01189ca4240f88ec44ce0893773bfe699d597

* libcloudforensics preset is used for building the project
* cloud-forensics-utils is used for building the analysis VM dependencies

Closing issue
