### ISSUE TITLE
Add ppc64le test target for Ubuntu on Travis

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/l2tdevtools#915]
Related to https://github.com/log2timeline/dfdatetime/pull/172#issuecomment-698505726

Determine if GIFT PPA ppc64le builds are needed

**Comment by joachimmetz** [comment]
dpkg control file `Architecture: powerpc ppc64 ppc64el` which likely will require changes and additional builds first

**Comment by sanjay-cpu** [comment]
> Related to [log2timeline/dfdatetime#172 (comment)](https://github.com/log2timeline/dfdatetime/pull/172#issuecomment-698505726)
> 
> Determine if GIFT PPA ppc64le builds are needed

@joachimmetz  if i am trying to execute this "docker exec ${CONTAINER_NAME} dnf copr -y enable @gift/dev;" command on ppc64le  then getting below error: 

"Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.
The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.
Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.
Error: Such repository does not exist.
The command "./config/travis/install.sh" failed and exited with 1 during . "

**Comment by sanjay-cpu** [comment]
> ~Change PPA setting on launchpad to include ppc64le target~
> 
> Looks like builds need to be retriggered

@joachimmetz yes, retriggering of failed one is getting passed.  Thanks !!

**Comment by joachimmetz** [comment]
> @joachimmetz if i am trying to execute this "docker exec ${CONTAINER_NAME} dnf copr -y enable @gift/dev;" command on ppc64le then getting below error:

@sanjay-cpu I would recommend to leave this up to me. Per the other issue, there is no COPR (Fedora) PPC64 test needed

> @joachimmetz yes, retriggering of failed one is getting passed. Thanks !!

I don't understand this comment, my comment has nothing to do with "failed builds"

**Comment by sanjay-cpu** [comment]
> > @joachimmetz if i am trying to execute this "docker exec ${CONTAINER_NAME} dnf copr -y enable @gift/dev;" command on ppc64le then getting below error:
> 
> @sanjay-cpu I would recommend to leave this up to me. Per the other issue, there is no COPR (Fedora) PPC64 test needed
> 
> > @joachimmetz yes, retriggering of failed one is getting passed. Thanks !!
> 
> I don't understand this comment, my comment has nothing to do with "failed builds"

@joachimmetz Ok, Thanks !!

**Comment by joachimmetz** [comment]
Added l2tbinaries ppc64le tests https://github.com/log2timeline/l2tbinaries/commit/5c4fde6db2b23763a4a9d4d46c9ecdc80f7f9502

**Comment by joachimmetz** [comment]
I don't see a ppc64le architecture in COPR.

**Comment by joachimmetz** [comment]
Binary Plaso dependencies in GIFT PPA updated to provide ppc64le build. Tests are failing because `[FAILURE]	psutil version: 5.4.2 is too old, 5.4.3 or later required`. Trying pushing new build on GIFT PPA

**Comment by joachimmetz** [comment]
Updated templates https://github.com/log2timeline/l2tdevtools/pull/917

Testing with dfdatetime https://github.com/log2timeline/dfdatetime/pull/173

**Comment by joachimmetz** [comment]
Rolled out for most log2timeline projects, long-tail will catch up with next updates. Closing issue
