### ISSUE TITLE
Build package for networkx

### ISSUE THREAD

**Issue by berggren** [log2timeline/l2tdevtools#939]
Timesketch has a new dependency, the python package networkx.

https://github.com/networkx/networkx

Opening this issue to track adding this, and transient dependencies as well:
From https://github.com/networkx/networkx/blob/master/requirements/default.txt

```
decorator>=4.4
numpy>=1.19; platform_python_implementation!='PyPy' and python_version<'3.9'
scipy>=1.5; platform_python_implementation!='PyPy' and python_version<'3.9'
matplotlib>=3.3; platform_python_implementation!='PyPy' and python_version<'3.9'
pandas>=1.1; platform_python_implementation!='PyPy' and python_version<'3.9'
```

**Comment by joachimmetz** [comment]
Pushed to GIFT PPA testing and dev track
