### ISSUE TITLE
Build packages for prometheus-flask-exporter

### ISSUE THREAD

**Issue by berggren** [log2timeline/l2tdevtools#982]
Timesketch has a couple of new dependencies:

* prometheus_client
* prometheus-flask-exporter

prometheus_client do exist as a package on Ubuntu 20.04 already (python3-prometheus-client) so we should be good there. But we need to build a package for prometheus-flask-exporter

https://pypi.org/project/prometheus-flask-exporter/
https://github.com/rycus86/prometheus_flask_exporter

**Comment by joachimmetz** [comment]
Added configuration https://github.com/log2timeline/l2tdevtools/pull/990, now to test it

**Comment by joachimmetz** [comment]
annoyingly `-` and `_` are used interchanged, this causes download from pypi to fail, using github release instead.

**Comment by joachimmetz** [comment]
Package added to GIFT PPA
